export const CATEGORIES = [
    "Dinner",
    "Appetizer",
    "Breakfast",
    "Brunch",
    "Dessert",
    "Lunch",
    "Entree",
    "Side Dish",
    "Snack",
    "Bread",
    "Drink",
    "Cocktail",
    "Soup",
    "Beverage",
    "Sauce",
    "Pasta",
    "Salad",
    "Cake",
    "Condiment",
    "Sandwich",
    "Ingredient",
    "Pie",
    "Candy",
    "Jam / Jelly",
    "Spice Mix",
    "Coffee"
];


export const CUISINES = [
    "American",
    "World",
    "Asian",
    "Spanish",
    "Indian",
    "Tex-Mex",
    "French",
    "Mexican Inspired",
    "Mexican",
    "Lebanese",
    "Irish",
    "U.S.",
    "Fusion",
    "Italian",
    "Middle Eastern",
    "Southwestern",
    "Latin",
    "Southern",
    "Italian Inspired",
    "Asian Inspired",
    "Thai",
    "Canadian",
    "Jewish",
    "Greek",
    "Swedish",
    "Indian Inspired",
    "Hawaiian",
    "Japanese",
    "African",
    "Cajun",
    "Swiss",
    "Latin American",
    "Kosher",
    "Cuban",
    "Caribbean",
    "British",
    "Tex Mex",
    "European",
    "New England",
    "Greek Inspired",
    "German",
    "Jamaican",
    "Korean",
    "Mediterranean Inspired",
    "Scandinavian",
    "English",
    "Portuguese",
    "Sicilian",
    "South American",
    "Ukrainian",
    "Eastern European",
    "East And Southeast Asian",
    "New Zealand",
    "Australian",
    "North African",
    "Scottish",
    "Filipino",
    "Native American",
    "Russian",
    "Czech",
    "Inspired",
    "Korean Inspired",
    "Puerto Rican",
    "Belgian",
    "Dutch",
    "Pakistani",
    "Colombian",
    "Authentic",
    "Peruvian",
    "Norwegian",
    "West African"
];


export const COOKING_METHODS = [
    "Microwave",
    "Fry",
    "Grill",
    "Bake",
    "Boil",
    "Simmer",
    "Reduce",
    "Toast",
    "Sauté",
    "Char",
    "Roast",
    "Steam",
    "Smoke",
    "Sear",
    "Broil",
    "Stir-fry",
    "Poach",
    "Blanch",
    "Braise",
    "Cure",
    "Pressure cook",
    "Slow cook"
];


export const TOOLS = [
    "Microwave",
    "Skillet",
    "Cutting board",
    "Grill",
    "Thermometer",
    "Blender",
    "Pan",
    "Oven",
    "Whisk",
    "Saucepan",
    "Mixer",
    "Stockpot",
    "Casserole dish",
    "Baking dish",
    "Pot",
    "Colander",
    "Baking sheet",
    "Spatula",
    "Knife",
    "Measuring cup",
    "Roasting pan",
    "Waffle iron",
    "Food processor",
    "Slow cooker",
    "Mortar",
    "Frying pan",
    "Rolling pin",
    "Dutch oven",
    "Steamer",
    "Strainer",
    "Pressure cooker",
    "Ladle",
    "Wok",
    "Paring knife",
    "Mallet",
    "Griddle",
    "Tongs",
    "Mandoline",
    "Pizza cutter",
    "Grater",
    "Piping bag",
    "Juicer",
    "Baster",
    "Tenderizer",
    "Salad spinner",
    "Measuring spoon"
];


export const PAGE_SIZE = 8;

export const PROFILE_RECIPE_PAGE_SIZE = 4;